### ISSUE TITLE
CREATE EXTERNAL RESOURCE POOL (Transact-SQL)

### ISSUE THREAD

**Issue by SQLBigEyesDad** [MicrosoftDocs/sql-docs.ko-kr#110]
MAX_MEMORY_PERCENT =value
"... value is an integer with a default setting of 100...." 
--&gt; It seems default value is 20(not 100). It referenced SSMS or other Microsoft Document

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a77e9e99-bc3a-92f8-d911-cae7072e8a16
* Version Independent ID: 3a77b0d7-ae97-1ebe-cbff-ade8ebd2e0c8
* Content: [CREATE EXTERNAL RESOURCE POOL(Transact-SQL) - SQL Server](https://docs.microsoft.com/ko-kr/sql/t-sql/statements/create-external-resource-pool-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-external-resource-pool-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ko-kr/blob/live/docs/t-sql/statements/create-external-resource-pool-transact-sql.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by srvbpigh** [comment]
Hello, @SQLBigEyesDad
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2665](https://github.com/MicrosoftDocs/sql-docs/issues/2665) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @SQLBigEyesDad

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - 
https://github.com/MicrosoftDocs/sql-docs/issues/2665
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
